version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
              - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - run: npm install mocha-junit-reporter # just for CircleCI
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test-and-coverage
          command: npm run test:circleci
          environment:
            MOCHA_FILE: test-results/mocha/test-results.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_artifacts:
          path: coverage/node
          destination: coverage
workflows:
  version: 2
  test_and_coverage:
    jobs:
      - test